inherit_from:
  - ../../.rubocop.yml

plugins:
  - rubocop-minitest

inherit_mode:
  override:
    - Exclude

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'db/migrate/**/*'
